# 1. THE DEPLOYMENT (The Servers)
# This tells Kubernetes to spin up 2 identical copies (replicas) of your app
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-frontend
  labels:
    app: my-portfolio
spec:
  replicas: 5
  selector:
    matchLabels:
      app: my-portfolio
  template:
    metadata:
      labels:
        app: my-portfolio
    spec:
      containers:
      - name: web-app
        # Replace this with your actual Docker image URL when you have one!
        # For now, this just runs a standard NGINX web server to test it.
        image: 989496899166.dkr.ecr.us-east-1.amazonaws.com/timepass:39c3b85e198bce310a7d391279e700cd60cc41c2
        ports:
        - containerPort: 80

---
# 2. THE SERVICE (The Networking)
# This tells Kubernetes how to route internal traffic to those 2 replicas
apiVersion: v1
kind: Service
metadata:
  name: portfolio-frontend-svc
spec:
  selector:
    app: my-portfolio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
